language: rust

rust:
  # someday, but rls relies on nightly right now.
  # - stable
  # - beta
  - nightly

cache:
  - cargo

before_install:
  - nvm install 8.1.4
  - ./ci-scripts/rustfmt.sh

script:
  - cargo test
  - rustfmt --write-mode diff src/*
  - cd frontend && npm install && npm run test
