[package]
name = "rustdoc"
version = "0.1.0"
authors = ["steveklabnik <steve@steveklabnik.com>"]

[dependencies]
clap = "2.24.2"
handlebars = "0.26.2"
indicatif = "0.5.0"

[dependencies.rls-analysis]
git = "https://github.com/nrc/rls-analysis/"